msm: ipa: guard unused variables if debugfs is disabled
This silences the following compiler warnings:

../drivers/platform/msm/ipa/ipa_clients/ipa_gsb.c:67:13: error: unused variable
'dbg_buff' [-Werror,-Wunused-variable]
static char dbg_buff[IPA_GSB_MAX_MSG_LEN];
            ^
../drivers/platform/msm/ipa/ipa_clients/ipa_gsb.c:74:23: error: unused variable
'dent' [-Werror,-Wunused-variable]
static struct dentry *dent;
                      ^
../drivers/platform/msm/ipa/ipa_clients/ipa_gsb.c:75:23: error: unused variable
'dfile_stats' [-Werror,-Wunused-variable]
static struct dentry *dfile_stats;
                      ^

Signed-off-by: Julian Liu <wlootlxt123@gmail.com>